export default function (){
  return [
          {
            string_id:1,
            name:'Dragons',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:3,name:'Novoline',},
            src:"http://kazakovas.ru/kazino/img/dragonsdeep_gt_html.jpg",
            bonus:'9 Lines, Bonus',
          },
          {
            string_id:2,
            name:'Diamond',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:1,name:'Amatic',},
            src:"http://kazakovas.ru/kazino/img/diamonds_on_fire_original.jpg",
            bonus:'6 Lines, Bonus',
          },
          {
            string_id:3,
            name:'Keks',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:2,name:'Igrosoft',},
            src:"http://kazakovas.ru/kazino/img/keks_original.jpg",
            bonus:'10 Lines, Bonus',
          },
          {
            string_id:6,
            name:'KeksII',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:2,name:'Igrosoft',},
            src:"http://kazakovas.ru/kazino/img/keks_original.jpg",
            bonus:'15 Lines, Bonus',
          },
          {
            string_id:5,
            name:'DiamondII',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:1,name:'Amatic',},
            src:"http://kazakovas.ru/kazino/img/diamonds_on_fire_original.jpg",
            bonus:'12 Lines, Bonus',
          },
          {
            string_id:4,
            name:'DragonsII',
            description:'',
            format:'',
            type:'',
            tags:'',
            jackpot:'',
            Brand:{string_id:3,name:'Novoline',},
            src:"http://kazakovas.ru/kazino/img/dragonsdeep_gt_html.jpg",
            bonus:'5 Lines, Bonus',
          },
        ]
}